
-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 11:34:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lojadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lojadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojadb` DEFAULT CHARACTER SET utf8 ;
USE `lojadb` ;

-- -----------------------------------------------------
-- Table `lojadb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojadb`.`cliente` (
  `CPF` CHAR(11) NOT NULL,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(30) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojadb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojadb`.`produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(100) NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `codBarras` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProdutos_UNIQUE` (`idProduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojadb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojadb`.`pedido` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `dtPedido` DATETIME NOT NULL,
  `CPFcomprador` CHAR(11) NOT NULL,
  `idProduto` INT NOT NULL,
  `stats` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idPedidos`),
  UNIQUE INDEX `idpedidos_UNIQUE` (`idPedidos` ASC) VISIBLE,
  UNIQUE INDEX `CPFcomprador_UNIQUE` (`CPFcomprador` ASC) VISIBLE,
  INDEX `fk_pedido_produto1_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`CPFcomprador`)
    REFERENCES `lojadb`.`cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `lojadb`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
